config/routes.rb
UrlShortenerManager::Application.routes.draw do
  devise_for :users
  get "dashboard/index"
  root to: "dashboard#index"

  resources :users

  resources :log_short_links do
    collection do
      post "generate_link", :defaults => { :format => 'json' }
      post "delete_url", :defaults => { :format => 'json' }
      post "update_url", :defaults => { :format => 'json' }
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :get_origin_urls do
        collection do
          post "find_url_origin", :defaults => { :format => 'json' }
        end
      end
    end
  end

end

app/models/log_short_link.rb
class LogShortLink < ActiveRecord::Base
end

app/models/log_view_link.rb
class LogViewLink < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/get_origin_urls_controller.rb
module Api
  module V1
    class GetOriginUrlsController < ActionController::Base
      require 'socket'
        def find_url_origin
          ip = Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
          @lsl = LogShortLink.find_by(link_short:params[:url])

          if !@lsl.blank?
            ##id log_short_links
            ##navegador
            #ip
            newLog = LogViewLink.new
            newLog.log_short_link_id = @lsl.id
            newLog.os_view = params[:web_nav]
            newLog.ip_view = ip.ip_address
            newLog.save
          end

          render json: @lsl
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  layout :layout
  private

  def layout
    # only turn it off for login pages:
    is_a?(Devise::SessionsController) ? false : "application"
    # or turn layout off for every devise controller:
    # devise_controller? && "application"
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

    @link_logs = LogShortLink.where("user_id = ?", current_user.id)
  end
end

app/controllers/log_short_links_controller.rb
class LogShortLinksController < ApplicationController

  def generate_link
      print params.inspect

      created_code_status = false

      while !created_code_status  do
        #si se tuviera subdominios activos se realizaria una consulta para seleccionar una y agregarselo en lugar del localhost
        code_g = "http://localhost:3000/" + ([*('A'..'Z'),*('0'..'9'),*('a'..'z')]-%w(0 1 I O)).sample(8).join
        created_code_status = LogShortLink.find_by(:link_short => code_g).blank? ? true : false
      end

      sls_nA = {}
      @sls_n = LogShortLink.new
      @sls_n.link_original = params[:url_or]
      @sls_n.link_short = code_g
      @sls_n.status = true
      @sls_n.user_id = current_user.id

      if @sls_n.save
        print ">>>>>>>>>>>>>> " + @sls_n.id.to_s
        sls_nA[:id] = @sls_n.id
        sls_nA[:link_original] = @sls_n.link_original
        sls_nA[:created_at] = @sls_n.created_at.to_datetime.strftime("%d-%m-%Y")
        sls_nA[:link_short] = @sls_n.link_short
      end


      render :json => sls_nA
  end

  def delete_url
    @usl = LogShortLink.find(params[:id])
    @usl.destroy
    render :json => 200
  end

  def update_url
    @usl = LogShortLink.find(params[:id])
    @usl.update_attributes(:link_original => params[:url_new])
    render :json => 200
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'Usuario actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :last_name, :email, :password, :password_confirmation, :role_id, :store_id, :discount, :code_confirm)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/log_short_links_helper.rb
module LogShortLinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="col-sm-8 offset-sm-2">

  <table class="table table-sm" id="tbl_urlS">
    <thead>
      <colgroup>
      <col style="width: 50%"/>
      <col style="width: 25%"/>
      <col style="width: 15%"/>
      <col style="width: 5%"/>
      <col style="width: 5%"/>
      </colgroup>
    </thead>
    <% @link_logs.each do |l|  %>
    <tr id="<%=l.id%>" >
      <td style="font-size: 13px;" ><a href="<%= l.link_original%>"><%= l.link_original%></a></td>
      <td><a href="<%= l.link_short%>"><%= l.link_short%></a></td>
      <td><%= l.created_at.to_datetime.strftime("%d-%m-%Y")%></td>
      <td><button type="button" name="button" class="btn btn-sm btn-danger" onclick="deleteRow(this)" data-id-ls="<%= l.id%>"> - </button></td>
      <td><button type="button" name="button" class="btn btn-sm btn-warning" onclick="updateLink(this)" data-id-ls="<%= l.id%>"> ? </button></td>
    </tr>
    <%end%>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortenerManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag  "bootstrap.min.css", media: "" %>
</head>
<body>

  <% if user_signed_in? %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Dashboard", root_path, class: 'nav-link' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <label for="" class="nav-link">

              </label>
            </li>
            <li class="nav-item">
              <%= link_to (!current_user.name.blank? ? current_user.name : current_user.email), edit_user_path(:id => current_user.id), class: 'fa fa-sign-out nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'fa fa-sign-out nav-link' %>
            </li>
            <% else %>
              User Name
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="col-sm-6 offset-sm-3 input-group" style="margin-top: 25px;margin-bottom: 25px;">
      <input type="url" placeholder="http://enlace-a-recortar.com" pattern="https://.*" required class="form-control">
      <div class="input-group-append">
        <button class="btn btn-warning" type="button" id="btn_gnl">Acortar enlace</button>
      </div>
    </div>


    <%if notice %>
      <p class="notice alert alert-primary" role="alert"><%= notice %></p>
    <%end%>

    <%if alert %>
      <p class="alert alert alert-primary"><%= alert %></p>
    <%end%>


    <div id="modal_generic" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true" data-backdrop="static" data-keyboard="false">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header" id="header_MG">
          </div>
          <div class="modal-body" id="body_MG">
          </div>
          <div class="modal-footer" id="footer_MG">
          </div>
        </div>
      </div>
    </div>

  <%end%>
  <div class="col-sm-12 col-md-12 col-xl-12">
    <%= yield %>
  </div>
<%= javascript_include_tag "bootstrap.min.js" %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@user.errors.count, "error") %> El usuario no se ha podido guardar:</h4>

      <ul>
      <% @user.errors.messages.each do |msg| %>
        <li><%= msg[1].to_sentence %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-sm-6">

  <table class="table table-form ">
    <tbody>

      <tr class="table_row">
        <td>Nombre:</td>
        <td class="single-column"><%= f.text_field :name, :required => true, :placeholder => "Nombre ..." %></td>
      </tr>
      <tr class="table_row">
        <td>Email:</td>
        <td class="single-column"><%= f.email_field :email, :required => true, :placeholder => "Email ..." %></td>
      </tr>

      <tr class="table_row">
        <td>Contraseña:</td>
        <td class="single-column"><%= f.password_field :password, autocomplete: "off", :required => true %></td>
      </tr>
      <tr class="table_row">
        <td>Confirmación:</td>
        <td class="single-column"><%= f.password_field :password_confirmation, autocomplete: "off", :required => true %></td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= f.submit 'Guardar',id: 'save_new_user', class: 'btn btn-success update'%>
    <%= link_to 'Cancelar', root_path, class: 'btn btn-success' %>
  </div>
</div>

<%end%>

app/views/users/edit.html.erb
<h2 class="sub-header-form">Editar Usuario</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h3>Lista de usuarios</h3>

app/views/users/new.html.erb
<h2 class="sub-header-form">Nuevo Usuario</h2>

<%= render 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>